### ISSUE TITLE
Can't use this module

### ISSUE THREAD

**Issue by tejashah88** [nicekiwi/lowdb-adapter-aws-s3#1]
Due to the `.npmignore`, the files needed to load this module are not packaged when doing `npm install`. Please remove the `.npmignore` file.

**Comment by nicekiwi** [comment]
I'm a noob haha, you're right that it was unusable; but your PR didn't really fix it. The package needs to be backwards compatible with node v4+ so it needs to be compiled before being published. So just using the src directly does not fix it. 

I was publishing it wrong. Fixed in v1.1.2. Now correctly installs with the dist and lib directories included. :D thanks.
